### ISSUE TITLE
wheel package format

### ISSUE THREAD

**Issue by stonebig** [dask/partd#3]
It would be nice if partd could be published as a wheel on pypi

**Comment by mrocklin** [comment]
I'm curious why this came up.  `partd` is a relatively simple project.

I don't have experience building wheels.  If you provide the exact commands or config file necessary to build and upload a wheel then I'd be happy to do it.  I will note that there is already a conda package.

**Comment by stonebig** [comment]
hi Matthew,

The benefit of wheel package is that:
- there is no 'package' code execution during install,
- it's hopefully brings 'pypi' clother to a 'conda' logic:
   . non pythonic things apart,
   . for non-binary wheels at least.

Just do:

````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*
````

**Comment by jakirkham** [comment]
Wheel or not, I do agree with @stonebig that it would be nice if this found its way onto PyPI. It would give it greater visibility, if nothing else.

**Comment by mrocklin** [comment]
Oh, I mistakenly assumed that this was a dask issue.  My bad.  

Partd is on PyPI.  https://pypi.python.org/pypi/partd  

I've had odd response from PyPI's searching capabilities recently.  Can you verify that this is publicly visible?

**Comment by jakirkham** [comment]
No worries.

You're right. It is indeed there.

I tried to search on PyPI and Google and somehow missed it. Weird. Did you report it?

Maybe it is worth adding a badge or link or something to point to it on PyPI.

**Comment by mrocklin** [comment]
I haven't reported it.

Added badge in https://github.com/blaze/partd/commit/0bba429fde163850156441c03981849b7a41ee08

I'm curious how you both use `partd`.  This is used internally within dask and I'd be thrilled to learn that it was useful in other applications as well.

**Comment by stonebig** [comment]
I take it in winpython because it's written in the `extra_requires`of dask: no direct usage.

**Comment by jakirkham** [comment]
Not currently using. Only discovered it today.

**Comment by jcrist** [comment]
Partd is now available on pypi as a wheel (https://pypi.python.org/pypi/partd/). Closing.
