### ISSUE TITLE
Error with datetime while running tests

### ISSUE THREAD

**Issue by thrasibule** [dask/partd#31]
I'm getting this error while running the tests (docstring of tz_localize elided for brevity)

```
partd/tests/test_pandas.py:110: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
partd/pandas.py:175: in deserialize
    for (h, b) in zip(headers[2:], bytes[2:])]
partd/pandas.py:175: in <listcomp>
    for (h, b) in zip(headers[2:], bytes[2:])]
partd/pandas.py:143: in block_from_header_bytes
    values = pd.DatetimeIndex(values).tz_localize('utc').tz_convert(
/usr/lib/python3.7/site-packages/pandas/core/accessor.py:91: in f
    return self._delegate_method(name, *args, **kwargs)
/usr/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py:721: in _delegate_method
    result = operator.methodcaller(name, *args, **kwargs)(self._data)

E               TypeError: Already tz-aware, use tz_convert to convert.

/usr/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py:1049: TypeError
```
This is with pandas 0.24.1.
Tests run fine if I replace line 143 in pandas.py with just `values = pd.DatetimeIndex(values)`, it seems like pandas restores the timezone just fine, not sure which version it started to work.

**Comment by mrocklin** [comment]
cc @TomAugspurger @jrbourbeau

**Comment by TomAugspurger** [comment]
I was looking into this briefly last week. I'll pick that up again today.

Are we OK with setting partd's min pandas to 0.19.0 to match dask? Or can we go newer than if supporting a pandas that old is a pain?

**Comment by TomAugspurger** [comment]
Some context: pandas 0.24 is stricter with tz conversions.

0.19.0 correctly infers the Timezone for an array-like of Timestamp objects

```python
In [6]: pd.DatetimeIndex([pd.Timestamp('2000', tz='US/Central')])
Out[6]: DatetimeIndex(['2000-01-01 00:00:00-06:00'], dtype='datetime64[ns, US/Central]', freq=None)
```

so we should be ok with removing the tz_localize and bumping the min pandas version.

**Comment by mrocklin** [comment]
Happy to defer to you on pandas versions to support.  I see no reason for
partd to support older than what dask supports.

**Comment by mrocklin** [comment]
See also https://github.com/dask/dask/issues/4580
