### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [dask/partd#41]
```
 find . -iname '*.py'  | xargs -P 4 -I{} python3.8 -Wall -m py_compile {}      
                                      
./versioneer.py:421: DeprecationWarning: invalid escape sequence \s
  LONG_VERSION_PY['git'] = '''
```

**Comment by jakirkham** [comment]
Thanks for the issue @tirkarthi. Unfortunately I feel like I'm missing some context. Could you please fill in some more details about what you are running into? 🙂

**Comment by tirkarthi** [comment]
The warning was raised for invalid escape sequences from Python. It's bound to become a SyntaxWarning in future and an error later : https://bugs.python.org/issue32912 . But this file I assume is generated so I am not sure of fixing it here or upstream.

**Comment by jakirkham** [comment]
I see. Thanks for the clarification. 🙂

Would [raise here]( https://github.com/warner/python-versioneer/issues ).

**Comment by tirkarthi** [comment]
Yes, closing. There is https://github.com/warner/python-versioneer/issues/201 . Sorry for the noise.

**Comment by jakirkham** [comment]
No at all. Thanks for raising 🙂
