### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by j-bennet** [dask/partd#69]
https://github.com/dask/partd/pull/67 was merged, but not released, so we're still having failures in CI with nightly pandas.

Can we have a new release of `partd`?

**Comment by jrbourbeau** [comment]
Yeah, no problem -- I'll push one out

**Comment by jrbourbeau** [comment]
Will push this out tomorrow if no further comment

**Comment by QuLogic** [comment]
It would be nice to get #70 in as well, though I realize it's still draft.

**Comment by jrbourbeau** [comment]
@QuLogic do you have a moment to review https://github.com/dask/partd/pull/70?

**Comment by phofl** [comment]
cc @jrbourbeau

**Comment by jrbourbeau** [comment]
Closing as 1.4.1 is out on PyPI and conda-forge (xref https://github.com/conda-forge/partd-feedstock/pull/22)
